import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

interface Journal {
    entries: Array<{
        breakpoints: boolean;
        tag: string;
        when: number;
    }>;
}

const migrationsDirectory = join(process.cwd(), "src/db/generated-migrations");
const outputFile = join(process.cwd(), "src/db/migrations.ts");
const journal = JSON.parse(
    readFileSync(join(migrationsDirectory, "meta/_journal.json"), "utf8"),
) as Journal;

const entries = journal.entries.map((entry) => {
    const migrationSql = readFileSync(
        join(migrationsDirectory, `${entry.tag}.sql`),
        "utf8",
    );
    const sql = migrationSql.split("--> statement-breakpoint");
    const hash = createHash("sha256").update(migrationSql).digest("hex");

    return `    {
        folderMillis: ${entry.when},
        hash: "${hash}",
        bps: ${entry.breakpoints},
        sql: ${JSON.stringify(sql, null, 12)},
    },`;
});

const output = `import type { MigrationMeta } from "drizzle-orm/migrator";

// Generated by scripts/generate-client-migrations.ts. Do not edit manually.
export const migrations: MigrationMeta[] = [
${entries.join("\n")}
];
`;

writeFileSync(outputFile, output);
console.log(`Generated ${entries.length} client migration(s).`);
